title: My Blog
baseurl: "/"
header_pages:
  - index.md
  - categories.md

style: dark # dark (default), light or hacker
listen_for_clients_preferred_style: true # false (default) or true

plugins:
  - jekyll-seo-tag

markdown: kramdown

